T.I.M | Toolchain Documentation: /home/ben/Documents/Projects/tim/sw/asm/asm.c File Reference
asm.c File Reference
Assembler
Main source file for the assembler. Contains main function and argument parser.
#include "asm.h"
#include "asm_lex.h"
Functions
void usage (int argc, char **argv)
prints usage instructions for the program.
void parse_cmd_args (int argc, char **argv, asm_context *cxt)
Parses the command line arguments passed to the program into a program_context object.
int main (int argc, char **argv)
Main entry point for the application.
Detailed Description
Main source file for the assembler. Contains main function and argument parser.
Function Documentation
int main (int argc, char ** argv)
Main entry point for the application.
References ASCII, asm_calculate_addresses(), asm_emit_instructions(), asm_hash_table_new(), asm_lex_input_file(), asm_parse_token_stream(), BINARY, error, fatal, log, parse_cmd_args(), and usage().
void parse_cmd_args (int argc, char ** argv, asm_context * cxt)
Parses the command line arguments passed to the program into a program_context object.
References ASCII, BINARY, fatal, usage(), and warning.
Referenced by main().
void usage (int argc, char ** argv)
prints usage instructions for the program.
References tprintf.
Referenced by main(), and parse_cmd_args().